version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=gabriel
      - POSTGRESQL_PASSWORD=gabriel5124
      - POSTGRESQL_DATABASE=apisolid
